/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.game.telas;

import br.game.controle.FuncionarioDao;
import br.game.listerners.MostrarFuncionarioListener;
import br.game.modelo.Funcionario;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lemon
 */
public class MostrarFuncionarioFrame extends javax.swing.JInternalFrame {

    private MostrarFuncionarioListener listener = new MostrarFuncionarioListener(this);
    private PrincipalFrame principal;

    /**
     * Creates new form MostrarFuncionario
     */
    public MostrarFuncionarioFrame() {
        initComponents();
        iniciarLista();
//        listFuncionario.addFocusListener(listener);
        btEditar.addActionListener(listener);
        btEditar.setActionCommand("editar");
        btRemover.addActionListener(listener);
        btRemover.setActionCommand("remover");
        btVoltar.addActionListener(listener);
        btVoltar.setActionCommand("voltar");
        btPesquisar.addActionListener(listener);
        btPesquisar.setActionCommand("pesquisar");
    }

    public String getDadosPesquisa() {
        return txtPesquisa.getText();
    }

    public void Sair() {
        PrincipalFrame.telaMostraFuncionario = null;
        this.dispose();
    }

    public void setListFuncionario(List<Funcionario> lista) {
        listFuncionario.setListData(lista.toArray());
    }

    public void mostrarFuncionarioFrame() {
        Funcionario funcionario = (Funcionario) listFuncionario.getSelectedValue();
        principal.criarRegistroFunconario(funcionario);
        listFuncionario.setListData(new Object[]{});
    }

    public void setPrincipal(PrincipalFrame principal) {
        this.principal = principal;
    }

    public void removerFuncionario(){
        Funcionario funcionario = (Funcionario) listFuncionario.getSelectedValue();
        FuncionarioDao dao = new FuncionarioDao();
        dao.delete(funcionario);
        JOptionPane.showMessageDialog(this, "\"" +funcionario.getNome() + "\"" + " foi removido com sucesso.");
        listFuncionario.setListData(new Object[]{});
        iniciarLista();
    }
    
     public void iniciarLista() {
        FuncionarioDao dao = new FuncionarioDao();
        setListFuncionario(dao.getFuncionarioPorLista());
    }

    public void setObjeto(){
        listFuncionario.setModel(new DefaultListModel());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFuncionario = new javax.swing.JList();
        txtPesquisa = new javax.swing.JTextField();
        btEditar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(true);
        setTitle("Pesquisar Funcionários");
        setPreferredSize(new java.awt.Dimension(520, 435));

        btPesquisar.setText("Pesquisar");

        listFuncionario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(listFuncionario);

        btEditar.setText("Editar");

        btRemover.setText("Remover");

        btVoltar.setText("Voltar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(txtPesquisa))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listFuncionario;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
