/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.game.telas;

import br.game.listerners.PrincipalListener;


public class PrincipalFrame extends javax.swing.JFrame {

    public PrincipalFrame() {
        initComponents();
        jDesktopPane1.setLayout(null);
        PrincipalListener listener = new PrincipalListener(this);
        btRegistrar.addActionListener(listener);
        btRegistrar.setActionCommand("registrar");
        btRegistrarJogo.addActionListener(listener);
        btRegistrarJogo.setActionCommand("registrarJogo");
        btJogos.addActionListener(listener);
        btJogos.setActionCommand("mostrarJogos");
        btSair.addActionListener(listener);
        btSair.setActionCommand("Sair");
        menuItemExcluirJogos.addActionListener(listener);
        menuItemExcluirJogos.setActionCommand("excluirJogos");
        menuItemExcluirUsuario.addActionListener(listener);
        menuItemExcluirUsuario.setActionCommand("excluirUsuario");
        menuSair.addActionListener(listener);
        menuSair.setActionCommand("Sair");

    }
    PrincipalFrame frame ;
    static RegistrarFrame telaRegistrar = null;
    static RegistroJogosFrame telaRegistrarJogos = null;
    static ExcluirJogosFrame telaExcluirJogos = null;
    static ExcluirUsuariosFrame telaExcluirUsuarios = null;
    static MostrarJogosFrame telaJogos = null;

    public void criarRegistro() {
        
        if (telaRegistrar == null) {
            telaRegistrar = new RegistrarFrame();
            jDesktopPane1.add(telaRegistrar);
            
        }
        telaRegistrar.setVisible(true);
    }

    public void criarRegistroJogos() {
        if (telaRegistrarJogos == null) {
            telaRegistrarJogos = new RegistroJogosFrame();
            jDesktopPane1.add(telaRegistrarJogos);
        }
        telaRegistrarJogos.setVisible(true);

    }

    public void criarExcluirJogos() {
        if (telaExcluirJogos == null) {
            telaExcluirJogos = new ExcluirJogosFrame();
            jDesktopPane1.add(telaExcluirJogos);
        }
        telaExcluirJogos.setVisible(true);
    }

    public void criarExcluirUsuarios() {
        if (telaExcluirUsuarios == null) {
            telaExcluirUsuarios = new ExcluirUsuariosFrame();
            jDesktopPane1.add(telaExcluirUsuarios);
        }
        telaExcluirUsuarios.setVisible(true);
    }
    
    public void criarMostrarJogos(){
        if(telaJogos == null){
            telaJogos = new MostrarJogosFrame();
            jDesktopPane1.add(telaJogos);
        }
        telaJogos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btJogos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btRegistrarJogo = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        x12 = new javax.swing.JMenuItem();
        x1 = new javax.swing.JMenuItem();
        menuItemExcluirUsuario = new javax.swing.JMenuItem();
        menuItemExcluirJogos = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btJogos.setText("Jogos");

        jButton2.setText("Clientes");

        btRegistrar.setText("Cadastrar Clientes");

        jButton4.setText("Cadastrar Funcionários");

        btRegistrarJogo.setText("Cadastrar Jogos");

        btSair.setText("Sair");

        jButton7.setText(" Funcionários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btJogos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btRegistrarJogo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRegistrarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 410));

        jMenu1.setText("Menus");

        x12.setText("Registrar");
        jMenu1.add(x12);

        x1.setText("Registrar Jogo");
        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });
        jMenu1.add(x1);

        menuItemExcluirUsuario.setText("ExcluirUsuario");
        jMenu1.add(menuItemExcluirUsuario);

        menuItemExcluirJogos.setText("Excluir Jogo");
        jMenu1.add(menuItemExcluirJogos);

        menuSair.setText("Sair");
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogos;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btRegistrarJogo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemExcluirJogos;
    private javax.swing.JMenuItem menuItemExcluirUsuario;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem x1;
    private javax.swing.JMenuItem x12;
    // End of variables declaration//GEN-END:variables
}
