/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.game.telas;

import javax.swing.ImageIcon;
import br.game.listerners.RegistroJogosListener;
import br.game.modelo.Jogos;

public class RegistroJogosFrame extends javax.swing.JInternalFrame {

    private RegistroJogosListener listener = new RegistroJogosListener(this);

    /**
     * Creates new form Registro
     */
    public RegistroJogosFrame() {
        initComponents();
        
       // menuItemAdd.addActionListener(listener);
        //menuItemAdd.setActionCommand("Add");
        //menuItemExit.addActionListener(listener);
        //menuItemExit.setActionCommand("Exit");
    }

    public Jogos getJogo() {
        Jogos jogo = new Jogos();
        jogo.setNomeJogo(txtGameName.getText());
        jogo.setAnoJogo(txtGameYear.getText());
        jogo.setGeneroJogo(cbGameCat.getSelectedItem().toString());
        jogo.setPlataformaJogo(cbGamePlat.getSelectedItem().toString());
        jogo.setPrecoJogo(Double.parseDouble(txtGamePrice.getText()));

        return jogo;
    }
    
        public void Sair(){
        PrincipalFrame.telaRegistrarJogos = null;
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGameCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGameName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGameYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGamePrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbGamePlat = new javax.swing.JComboBox();
        cbGameCat = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setForeground(java.awt.Color.white);
        setTitle("Cadastro de Jogos");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 95, -1));
        getContentPane().add(txtGameCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 114, -1));

        jLabel2.setText("Nome do Jogo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 22, 110, -1));
        getContentPane().add(txtGameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 45, 130, -1));

        jLabel3.setText("Ano de Lançamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 78, -1, -1));
        getContentPane().add(txtGameYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 101, 130, -1));

        jLabel6.setText("Preço");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 95, -1));
        getContentPane().add(txtGamePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 114, -1));

        jLabel5.setText("Plataforma");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 100, -1));

        cbGamePlat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "Xbox 360", "Play Station 3", "Xbox One", "Play Station 4", "Nintendo 3ds", "Nintendo WiiU" }));
        cbGamePlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGamePlatActionPerformed(evt);
            }
        });
        getContentPane().add(cbGamePlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, 114, -1));

        cbGameCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FPS", "MOBA", "RPG", "MMORPG", "Ação", "Aventura", "Horror Psicológico" }));
        cbGameCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGameCatActionPerformed(evt);
            }
        });
        getContentPane().add(cbGameCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 157, 130, -1));

        jLabel4.setText("Categoria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 134, 80, -1));

        btCancel.setText("Voltar");
        btCancel.addActionListener(listener);
        btCancel.setActionCommand("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, -1));

        btAdd.setText("Adicionar");
        btAdd.addActionListener(listener);
        btAdd.setActionCommand("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 114, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelActionPerformed

    private void cbGameCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGameCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGameCatActionPerformed

    private void cbGamePlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGamePlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGamePlatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JComboBox cbGameCat;
    private javax.swing.JComboBox cbGamePlat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtGameCode;
    private javax.swing.JTextField txtGameName;
    private javax.swing.JTextField txtGamePrice;
    private javax.swing.JTextField txtGameYear;
    // End of variables declaration//GEN-END:variables
    ImageIcon icon = new ImageIcon("C:/Users/comp1/Documents/NetBeansProjects/Projeto1/GameLand/src/Items/games.jpg");

}
