/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import listeners.RegistroJogosListener;
import modelo.Jogos;

/**
 *
 * @author Lemon
 */
public class RegistroJogosFrame extends javax.swing.JInternalFrame {

    private RegistroJogosListener Jogoslistener = new RegistroJogosListener(this);
    
    
    
    /**
     * Creates new form Registro
     */
    public RegistroJogosFrame() {
        initComponents();
    }
    
    public Jogos getJogo()
    {
        Jogos jogo = new Jogos();
        jogo.setNomeJogo(txtGameName.getText());
        jogo.setAnoJogo(txtGameYear.getText());
        jogo.setGeneroJogo(cbGameCat.getSelectedItem().toString());
        jogo.setPlataformaJogo(cbGamePlat.getSelectedItem().toString());
        jogo.setPrecoJogo(Double.parseDouble(txtGamePrice.getText()));
    
        return jogo;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGameCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGameName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGameYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGamePrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbGamePlat = new javax.swing.JComboBox();
        cbGameCat = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();

        setBorder(null);
        setTitle("Cadastro de Jogos");
        setNormalBounds(new java.awt.Rectangle(0, 0, 100, 200));
        setPreferredSize(new java.awt.Dimension(350, 500));
        setVisible(true);

        jLabel1.setText("Código");

        jLabel2.setText("Nome do Jogo");

        jLabel3.setText("Ano de Lançamento");

        jLabel6.setText("Preço");

        jLabel5.setText("Plataforma");

        cbGamePlat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "Xbox 360", "Play Station 3", "Xbox One", "Play Station 4", "Nintendo 3ds", "Nintendo WiiU" }));

        cbGameCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FPS", "MOBA", "RPG", "MMORPG", "Ação", "Aventura", "Horror Psicológico" }));
        cbGameCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGameCatActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria");

        btCancel.setText("Cancelar");
        btCancel.addActionListener(Jogoslistener);
        btCancel.setActionCommand("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btAdd.setText("Adicionar");
        btAdd.addActionListener(Jogoslistener);
        btAdd.setActionCommand("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGamePlat, 0, 114, Short.MAX_VALUE)
                    .addComponent(txtGamePrice)
                    .addComponent(txtGameCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGameName)
                    .addComponent(txtGameYear)
                    .addComponent(cbGameCat, 0, 167, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGameCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGamePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGameYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGamePlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGameCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelActionPerformed

    private void cbGameCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGameCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGameCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JComboBox cbGameCat;
    private javax.swing.JComboBox cbGamePlat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtGameCode;
    private javax.swing.JTextField txtGameName;
    private javax.swing.JTextField txtGamePrice;
    private javax.swing.JTextField txtGameYear;
    // End of variables declaration//GEN-END:variables
    ImageIcon icon = new ImageIcon("C:/Users/comp1/Documents/NetBeansProjects/Projeto1/GameLand/src/Items/games.jpg"); 

}
